openapi: 3.2.0
info:
  title: Deputy Resource API
  version: '1.0'
  contact: {}
  description: 'Operations tagged Resource API across 2 of this provider''s published API definitions: deputy-deputy-openapi.yml, deputy-resource-api-openapi.yml. Each path carries the servers of the definition it was published in.'
servers:
- url: https://{install}.{geo}.deputy.com/api
  variables:
    install:
      default: ''
    geo:
      default: ''
- url: https://{install}.{geo}.deputy.com/api/v1/resource
  variables: {}
security:
- httpBearer: []
tags:
- name: Resource API
paths:
  /v1/resource/Employee/{employeeid}:
    get:
      tags:
      - Resource API
      summary: Example - Search for employees from a location
      operationId: Example-Searchforemployeesfromalocation
      parameters:
      - name: employeeid
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
          content: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api
      variables:
        install:
          default: ''
        geo:
          default: ''
  /Address:
    get:
      tags:
      - Resource API
      summary: Get Addresses
      operationId: GetAddresses
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /Address/INFO:
    get:
      tags:
      - Resource API
      summary: Get Address Object Info
      operationId: GetAddressObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /Address/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for address
      operationId: Searchforaddress
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforaddressRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /Category:
    get:
      tags:
      - Resource API
      summary: Get Categories
      operationId: GetCategories
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /Category/INFO:
    get:
      tags:
      - Resource API
      summary: Get Category Object Info
      operationId: GetCategoryObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /Category/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for Category
      operationId: SearchforCategory
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforCategoryRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /Comment:
    get:
      tags:
      - Resource API
      summary: Get Comments
      operationId: GetComments
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /Comment/INFO:
    get:
      tags:
      - Resource API
      summary: Get Comment Object Info
      operationId: GetCommentObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /Comment/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for a comment
      operationId: Searchforacomment
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforacommentRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /Company:
    get:
      tags:
      - Resource API
      summary: Get Locations
      operationId: GetLocations
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - Resource API
      summary: Search for a Location
      operationId: SearchforaLocation
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforaLocationRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /Company/INFO:
    get:
      tags:
      - Resource API
      summary: Get Locations Object Info
      operationId: GetLocationsObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /CompanyPeriod:
    get:
      tags:
      - Resource API
      summary: Get Company Periods
      operationId: GetCompanyPeriods
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /CompanyPeriod/INFO:
    get:
      tags:
      - Resource API
      summary: Get Company Period Object Info
      operationId: GetCompanyPeriodObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /CompanyPeriod/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for a Company Period
      operationId: SearchforaCompanyPeriod
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforaCompanyPeriodRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /Contact/INFO:
    get:
      tags:
      - Resource API
      summary: Get Contact Object Info
      operationId: GetContactObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /Contact/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for a contact
      operationId: Searchforacontact
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforacontactRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /Country/INFO:
    get:
      tags:
      - Resource API
      summary: Get Country Object Info
      operationId: GetCountryObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /Country/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for a country
      operationId: Searchforacountry
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforacountryRequest'
              - example:
                  search:
                    s1:
                      field: Code
                      data: au
                      type: eq
            example:
              search:
                s1:
                  field: Code
                  data: au
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /CustomAppData:
    get:
      tags:
      - Resource API
      summary: Get Custom App Data entries
      operationId: GetCustomAppDataentries
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /CustomAppData/INFO:
    get:
      tags:
      - Resource API
      summary: Get Custom App Data Object Info
      operationId: GetCustomAppDataObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /CustomAppData/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for a custom app data entry
      operationId: Searchforacustomappdataentry
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforacustomappdataentryRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /CustomField:
    get:
      tags:
      - Resource API
      summary: Get Custom Fields
      operationId: GetCustomFields
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - Resource API
      summary: Search for a Custom Field
      operationId: SearchforaCustomField
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforaCustomFieldRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /CustomField/INFO:
    get:
      tags:
      - Resource API
      summary: Get Custom Field Object Info
      operationId: GetCustomFieldObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /CustomField/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for a custom field data entry
      operationId: Searchforacustomfielddataentry
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforacustomfielddataentryRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /CustomFieldData/INFO:
    get:
      tags:
      - Resource API
      summary: Get Custom Field Data Object Info
      operationId: GetCustomFieldDataObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /Employee/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employee Object Info
      operationId: GetEmployeeObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /Employee/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for an employee
      operationId: Searchforanemployee
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanemployeeRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmployeeAgreement:
    get:
      tags:
      - Resource API
      summary: Get Employee Agreements
      operationId: GetEmployeeAgreements
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmployeeAgreement/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employee Agreement Object Info
      operationId: GetEmployeeAgreementObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmployeeAgreement/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for an employee agreement
      operationId: Searchforanemployeeagreement
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanemployeeagreementRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmployeeAgreementHistory:
    get:
      tags:
      - Resource API
      summary: Get Employee Agreement History
      operationId: GetEmployeeAgreementHistory
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmployeeAgreementHistory/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employee Agreement History Object Info
      operationId: GetEmployeeAgreementHistoryObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmployeeAgreementHistory/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for an Employee Agreement History
      operationId: SearchforanEmployeeAgreementHistory
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanEmployeeAgreementHistoryRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmployeeAppraisal:
    get:
      tags:
      - Resource API
      summary: Get Employee Appraisals
      operationId: GetEmployeeAppraisals
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - Resource API
      summary: Search for an Employee Appraisal
      operationId: SearchforanEmployeeAppraisal
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanEmployeeAppraisalRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmployeeAppraisal/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employee Appraisal Object Info
      operationId: GetEmployeeAppraisalObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmployeeAvailability:
    get:
      tags:
      - Resource API
      summary: Get Employee Availability
      operationId: GetEmployeeAvailability
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmployeeAvailability/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employee Availability Object Info
      operationId: GetEmployeeAvailabilityObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmployeeAvailability/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for an Employee Availability
      operationId: SearchforanEmployeeAvailability
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanEmployeeAvailabilityRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmployeeHistory:
    get:
      tags:
      - Resource API
      summary: Get Employee History
      operationId: GetEmployeeHistory
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmployeeHistory/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employee History Object Info
      operationId: GetEmployeeHistoryObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmployeeHistory/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for an Employee History
      operationId: SearchforanEmployeeHistory
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanEmployeeHistoryRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmployeeRole:
    get:
      tags:
      - Resource API
      summary: Get Employee Roles
      operationId: GetEmployeeRoles
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmployeeRole/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employee Role Object Info
      operationId: GetEmployeeRoleObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmployeeRole/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for an Employee Role
      operationId: SearchforanEmployeeRole
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanEmployeeRoleRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmployeeWorkplace:
    get:
      tags:
      - Resource API
      summary: Get Employee Workplaces
      operationId: GetEmployeeWorkplaces
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - Resource API
      summary: Search for an Employee Workplace
      operationId: SearchforanEmployeeWorkplace
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanEmployeeWorkplaceRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmploymentCondition:
    get:
      tags:
      - Resource API
      summary: Get Employment Conditions
      operationId: GetEmploymentConditions
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmploymentCondition/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employment Condition Object Info
      operationId: GetEmploymentConditionObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmploymentCondition/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for an Employment Condition
      operationId: SearchforanEmploymentCondition
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanEmploymentConditionRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmploymentContract/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employment Contract Object Info
      operationId: GetEmploymentContractObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmploymentContract/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for an Employment Contract
      operationId: SearchforanEmploymentContract
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanEmploymentContractRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmploymentContractLeaveRules:
    get:
      tags:
      - Resource API
      summary: Get Employment Contract Leave Rules
      operationId: GetEmploymentContractLeaveRules
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - Resource API
      summary: Search for Employment Contract Leave Rules
      operationId: SearchforEmploymentContractLeaveRules
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforEmploymentContractLeaveRulesRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /EmploymentContractLeaveRules/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employment Contract Leave Rules Object Info
      operationId: GetEmploymentContractLeaveRulesObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /Event:
    get:
      tags:
      - Resource API
      summary: Get Events
      operationId: GetEvents
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /Event/INFO:
    get:
      tags:
      - Resource API
      summary: Get Event Object Info
      operationId: GetEventObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
  /Event/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for Events
      operationId: SearchforEvents
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforEventsRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    servers:
    - url: https://{install}.{geo}.deputy.com/api/v1/resource
      variables: {}
components:
  schemas:
    Search:
      title: Search
      required:
      - s1
      type: object
      properties:
        s1:
          $ref: '#/components/schemas/S1'
      example:
        s1:
          field: Id
          data: 1
          type: eq
    SearchforanEmployeeWorkplaceRequest:
      title: SearchforanEmployeeWorkplaceRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforanemployeeRequest:
      title: SearchforanemployeeRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforacommentRequest:
      title: SearchforacommentRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforanEmployeeAgreementHistoryRequest:
      title: SearchforanEmployeeAgreementHistoryRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforanEmployeeAppraisalRequest:
      title: SearchforanEmployeeAppraisalRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforanEmploymentConditionRequest:
      title: SearchforanEmploymentConditionRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforaCustomFieldRequest:
      title: SearchforaCustomFieldRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforacountryRequest:
      title: SearchforacountryRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search6'
      example:
        search:
          s1:
            field: Code
            data: au
            type: eq
    SearchforanEmployeeRoleRequest:
      title: SearchforanEmployeeRoleRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforEventsRequest:
      title: SearchforEventsRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforaddressRequest:
      title: SearchforaddressRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    S16:
      title: S16
      required:
      - field
      - data
      - type
      type: object
      properties:
        field:
          type: string
        data:
          type: string
        type:
          type: string
      example:
        field: Code
        data: au
        type: eq
    SearchforanEmployeeHistoryRequest:
      title: SearchforanEmployeeHistoryRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforanEmploymentContractRequest:
      title: SearchforanEmploymentContractRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforCategoryRequest:
      title: SearchforCategoryRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforacustomappdataentryRequest:
      title: SearchforacustomappdataentryRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    S1:
      title: S1
      required:
      - field
      - data
      - type
      type: object
      properties:
        field:
          type: string
        data:
          type: integer
          format: int32
        type:
          type: string
      example:
        field: Id
        data: 1
        type: eq
    SearchforaLocationRequest:
      title: SearchforaLocationRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforanemployeeagreementRequest:
      title: SearchforanemployeeagreementRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforacontactRequest:
      title: SearchforacontactRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforacustomfielddataentryRequest:
      title: SearchforacustomfielddataentryRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforanEmployeeAvailabilityRequest:
      title: SearchforanEmployeeAvailabilityRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforaCompanyPeriodRequest:
      title: SearchforaCompanyPeriodRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    Search6:
      title: Search6
      required:
      - s1
      type: object
      properties:
        s1:
          $ref: '#/components/schemas/S16'
      example:
        s1:
          field: Code
          data: au
          type: eq
    SearchforEmploymentContractLeaveRulesRequest:
      title: SearchforEmploymentContractLeaveRulesRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
x-refined-from:
- deputy-deputy-openapi.yml
- deputy-resource-api-openapi.yml
x-provenance:
  method: searched
  source: https://developer.deputy.com/reference
  harvested: '2026-10-14'
  tool: harvest-readme-openapi.py
  note: Assembled verbatim from the OpenAPI definition ReadMe embeds in each operation page of the provider's developer portal; paths and components merged by API title, nothing authored.
  assembled_from:
  - https://developer.deputy.com/reference/addalocation.md
  - https://developer.deputy.com/reference/addalocationagainstanemployee.md
  - https://developer.deputy.com/reference/addanemployee.md
  - https://developer.deputy.com/reference/addasaletosalesmetrics.md
  - https://developer.deputy.com/reference/addawebhookurl.md
  - https://developer.deputy.com/reference/addleaveforaemployee.md
  - https://developer.deputy.com/reference/addnewworkplace.md
  - https://developer.deputy.com/reference/addunavailabilitydetailsforaemployee.md
  - https://developer.deputy.com/reference/archivealocation.md
  - https://developer.deputy.com/reference/copyaroster.md
  - https://developer.deputy.com/reference/create-a-memo.md
  - https://developer.deputy.com/reference/createadepartment.md
  - https://developer.deputy.com/reference/createmultipledepartments.md
  - https://developer.deputy.com/reference/deletealocation.md
  - https://developer.deputy.com/reference/deleteanemployeesaccountindeputy.md
  - https://developer.deputy.com/reference/deleteasingleoperationalunit.md
  - https://developer.deputy.com/reference/discardaroster.md
  - https://developer.deputy.com/reference/doatask.md
  - https://developer.deputy.com/reference/example-searchforemployeesfromalocation.md
  - https://developer.deputy.com/reference/findanemployeesleave.md
  - https://developer.deputy.com/reference/findoutanemployeesstatus.md
  - https://developer.deputy.com/reference/getagreedhoursbyemployeeid.md
  - https://developer.deputy.com/reference/getalistofrostersfromlast12hoursandforward36hours.md
  - https://developer.deputy.com/reference/getalocationssettings.md
  - https://developer.deputy.com/reference/getawardslibrarylist.md
  - https://developer.deputy.com/reference/getdetailsforaemployeebyid.md
  - https://developer.deputy.com/reference/getdetailsforallemployees.md
  - https://developer.deputy.com/reference/getlocationbyid.md
  - https://developer.deputy.com/reference/getlocations.md
  - https://developer.deputy.com/reference/getmyindividualtimesheet.md
  - https://developer.deputy.com/reference/getmynewsfeed.md
  - https://developer.deputy.com/reference/getmynotifications.md
  - https://developer.deputy.com/reference/getmysubordinatecontactdetails.md
  - https://developer.deputy.com/reference/getmytasks.md
  - https://developer.deputy.com/reference/getmytimesheets.md
  - https://developer.deputy.com/reference/getmytraining.md
  - https://developer.deputy.com/reference/getoperationalunits.md
  - https://developer.deputy.com/reference/getrostersavailableforswap.md
  - https://developer.deputy.com/reference/getsimplifiedlocationlist.md
  - https://developer.deputy.com/reference/getsuggestionsforrosterbyid.md
  - https://developer.deputy.com/reference/getunavailabilitydetailsforaemployee.md
  - https://developer.deputy.com/reference/inviteemployeetodeputy.md
  - https://developer.deputy.com/reference/modifysettingsinalllocations.md
  - https://developer.deputy.com/reference/modifysettingsinasinglelocation.md
  - https://developer.deputy.com/reference/myaddressonfile.md
  - https://developer.deputy.com/reference/myaddressonfileincludingemergency.md
  - https://developer.deputy.com/reference/myleaverequests.md
  - https://developer.deputy.com/reference/pauseorunpauseemployeestimesheettakeabreakfinishbreak.md
  - https://developer.deputy.com/reference/postajournal.md
  - https://developer.deputy.com/reference/publisharoster.md
  - https://developer.deputy.com/reference/re-activateaterminatedemployee.md
  - https://developer.deputy.com/reference/removealocationfromanemployee.md
  - https://developer.deputy.com/reference/retrievecurrentsystemtime.md
  - https://developer.deputy.com/reference/retrievecurrentsystemtimeofalocation.md
  - https://developer.deputy.com/reference/retrievesalesdata.md
  - https://developer.deputy.com/reference/setawardforemployee.md
  - https://developer.deputy.com/reference/startanemployeestimesheetclockon.md
  - https://developer.deputy.com/reference/stopanemployeestimesheetclockoff.md
  - https://developer.deputy.com/reference/terminateanemployee.md
  - https://developer.deputy.com/reference/updatealocation.md
  - https://developer.deputy.com/reference/updateanexistingemployee.md
  - https://developer.deputy.com/reference/updateasingleoperationalunit.md
  - https://developer.deputy.com/reference/updatemyaddress.md
  - https://developer.deputy.com/reference/viewatimesheetbyid.md
  - https://developer.deputy.com/reference/whatlocationscaniworkin.md
  - https://developer.deputy.com/reference/whenaminextworking.md
  - https://developer.deputy.com/reference/whenamiunavailable.md
  - https://developer.deputy.com/reference/wherecaniworkwhatdoido.md
  - https://developer.deputy.com/reference/whodoiworkwith.md
  merge:
    pages: 69
    deduped: 70
    conflicts_kept_first: 0
