openapi: 3.0.0
info:
  title: Deputy Resource API
  contact: {}
  version: '1.0'
servers:
- url: https://{install}.{geo}.deputy.com/api/v1/resource
  variables: {}
security:
- httpBearer: []
paths:
  /Address:
    get:
      tags:
      - Resource API
      summary: Get Addresses
      operationId: GetAddresses
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /Address/INFO:
    get:
      tags:
      - Resource API
      summary: Get Address Object Info
      operationId: GetAddressObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /Address/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for address
      operationId: Searchforaddress
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforaddressRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /Category:
    get:
      tags:
      - Resource API
      summary: Get Categories
      operationId: GetCategories
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /Category/INFO:
    get:
      tags:
      - Resource API
      summary: Get Category Object Info
      operationId: GetCategoryObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /Category/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for Category
      operationId: SearchforCategory
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforCategoryRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /Comment:
    get:
      tags:
      - Resource API
      summary: Get Comments
      operationId: GetComments
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /Comment/INFO:
    get:
      tags:
      - Resource API
      summary: Get Comment Object Info
      operationId: GetCommentObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /Comment/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for a comment
      operationId: Searchforacomment
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforacommentRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /Company:
    get:
      tags:
      - Resource API
      summary: Get Locations
      operationId: GetLocations
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - Resource API
      summary: Search for a Location
      operationId: SearchforaLocation
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforaLocationRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /Company/INFO:
    get:
      tags:
      - Resource API
      summary: Get Locations Object Info
      operationId: GetLocationsObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /CompanyPeriod:
    get:
      tags:
      - Resource API
      summary: Get Company Periods
      operationId: GetCompanyPeriods
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /CompanyPeriod/INFO:
    get:
      tags:
      - Resource API
      summary: Get Company Period Object Info
      operationId: GetCompanyPeriodObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /CompanyPeriod/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for a Company Period
      operationId: SearchforaCompanyPeriod
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforaCompanyPeriodRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /Contact/INFO:
    get:
      tags:
      - Resource API
      summary: Get Contact Object Info
      operationId: GetContactObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /Contact/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for a contact
      operationId: Searchforacontact
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforacontactRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /Country/INFO:
    get:
      tags:
      - Resource API
      summary: Get Country Object Info
      operationId: GetCountryObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /Country/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for a country
      operationId: Searchforacountry
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforacountryRequest'
              - example:
                  search:
                    s1:
                      field: Code
                      data: au
                      type: eq
            example:
              search:
                s1:
                  field: Code
                  data: au
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /CustomAppData:
    get:
      tags:
      - Resource API
      summary: Get Custom App Data entries
      operationId: GetCustomAppDataentries
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /CustomAppData/INFO:
    get:
      tags:
      - Resource API
      summary: Get Custom App Data Object Info
      operationId: GetCustomAppDataObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /CustomAppData/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for a custom app data entry
      operationId: Searchforacustomappdataentry
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforacustomappdataentryRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /CustomField:
    get:
      tags:
      - Resource API
      summary: Get Custom Fields
      operationId: GetCustomFields
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - Resource API
      summary: Search for a Custom Field
      operationId: SearchforaCustomField
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforaCustomFieldRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /CustomField/INFO:
    get:
      tags:
      - Resource API
      summary: Get Custom Field Object Info
      operationId: GetCustomFieldObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /CustomField/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for a custom field data entry
      operationId: Searchforacustomfielddataentry
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforacustomfielddataentryRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /CustomFieldData/INFO:
    get:
      tags:
      - Resource API
      summary: Get Custom Field Data Object Info
      operationId: GetCustomFieldDataObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /Employee/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employee Object Info
      operationId: GetEmployeeObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /Employee/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for an employee
      operationId: Searchforanemployee
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanemployeeRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmployeeAgreement:
    get:
      tags:
      - Resource API
      summary: Get Employee Agreements
      operationId: GetEmployeeAgreements
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmployeeAgreement/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employee Agreement Object Info
      operationId: GetEmployeeAgreementObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmployeeAgreement/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for an employee agreement
      operationId: Searchforanemployeeagreement
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanemployeeagreementRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmployeeAgreementHistory:
    get:
      tags:
      - Resource API
      summary: Get Employee Agreement History
      operationId: GetEmployeeAgreementHistory
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmployeeAgreementHistory/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employee Agreement History Object Info
      operationId: GetEmployeeAgreementHistoryObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmployeeAgreementHistory/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for an Employee Agreement History
      operationId: SearchforanEmployeeAgreementHistory
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanEmployeeAgreementHistoryRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmployeeAppraisal:
    get:
      tags:
      - Resource API
      summary: Get Employee Appraisals
      operationId: GetEmployeeAppraisals
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - Resource API
      summary: Search for an Employee Appraisal
      operationId: SearchforanEmployeeAppraisal
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanEmployeeAppraisalRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmployeeAppraisal/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employee Appraisal Object Info
      operationId: GetEmployeeAppraisalObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmployeeAvailability:
    get:
      tags:
      - Resource API
      summary: Get Employee Availability
      operationId: GetEmployeeAvailability
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmployeeAvailability/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employee Availability Object Info
      operationId: GetEmployeeAvailabilityObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmployeeAvailability/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for an Employee Availability
      operationId: SearchforanEmployeeAvailability
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanEmployeeAvailabilityRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmployeeHistory:
    get:
      tags:
      - Resource API
      summary: Get Employee History
      operationId: GetEmployeeHistory
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmployeeHistory/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employee History Object Info
      operationId: GetEmployeeHistoryObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmployeeHistory/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for an Employee History
      operationId: SearchforanEmployeeHistory
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanEmployeeHistoryRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmployeeRole:
    get:
      tags:
      - Resource API
      summary: Get Employee Roles
      operationId: GetEmployeeRoles
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmployeeRole/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employee Role Object Info
      operationId: GetEmployeeRoleObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmployeeRole/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for an Employee Role
      operationId: SearchforanEmployeeRole
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanEmployeeRoleRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmployeeWorkplace:
    get:
      tags:
      - Resource API
      summary: Get Employee Workplaces
      operationId: GetEmployeeWorkplaces
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - Resource API
      summary: Search for an Employee Workplace
      operationId: SearchforanEmployeeWorkplace
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanEmployeeWorkplaceRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmploymentCondition:
    get:
      tags:
      - Resource API
      summary: Get Employment Conditions
      operationId: GetEmploymentConditions
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmploymentCondition/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employment Condition Object Info
      operationId: GetEmploymentConditionObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmploymentCondition/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for an Employment Condition
      operationId: SearchforanEmploymentCondition
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanEmploymentConditionRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmploymentContract/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employment Contract Object Info
      operationId: GetEmploymentContractObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmploymentContract/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for an Employment Contract
      operationId: SearchforanEmploymentContract
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforanEmploymentContractRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmploymentContractLeaveRules:
    get:
      tags:
      - Resource API
      summary: Get Employment Contract Leave Rules
      operationId: GetEmploymentContractLeaveRules
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    post:
      tags:
      - Resource API
      summary: Search for Employment Contract Leave Rules
      operationId: SearchforEmploymentContractLeaveRules
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforEmploymentContractLeaveRulesRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /EmploymentContractLeaveRules/INFO:
    get:
      tags:
      - Resource API
      summary: Get Employment Contract Leave Rules Object Info
      operationId: GetEmploymentContractLeaveRulesObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /Event:
    get:
      tags:
      - Resource API
      summary: Get Events
      operationId: GetEvents
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /Event/INFO:
    get:
      tags:
      - Resource API
      summary: Get Event Object Info
      operationId: GetEventObjectInfo
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /Event/QUERY:
    post:
      tags:
      - Resource API
      summary: Search for Events
      operationId: SearchforEvents
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SearchforEventsRequest'
              - example:
                  search:
                    s1:
                      field: Id
                      data: 1
                      type: eq
            example:
              search:
                s1:
                  field: Id
                  data: 1
                  type: eq
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
components:
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
  schemas:
    SearchforaddressRequest:
      title: SearchforaddressRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    Search:
      title: Search
      required:
      - s1
      type: object
      properties:
        s1:
          $ref: '#/components/schemas/S1'
      example:
        s1:
          field: Id
          data: 1
          type: eq
    S1:
      title: S1
      required:
      - field
      - data
      - type
      type: object
      properties:
        field:
          type: string
        data:
          type: integer
          format: int32
        type:
          type: string
      example:
        field: Id
        data: 1
        type: eq
    SearchforCategoryRequest:
      title: SearchforCategoryRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforacommentRequest:
      title: SearchforacommentRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforaLocationRequest:
      title: SearchforaLocationRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforaCompanyPeriodRequest:
      title: SearchforaCompanyPeriodRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforacontactRequest:
      title: SearchforacontactRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforacountryRequest:
      title: SearchforacountryRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search6'
      example:
        search:
          s1:
            field: Code
            data: au
            type: eq
    Search6:
      title: Search6
      required:
      - s1
      type: object
      properties:
        s1:
          $ref: '#/components/schemas/S16'
      example:
        s1:
          field: Code
          data: au
          type: eq
    S16:
      title: S16
      required:
      - field
      - data
      - type
      type: object
      properties:
        field:
          type: string
        data:
          type: string
        type:
          type: string
      example:
        field: Code
        data: au
        type: eq
    SearchforacustomappdataentryRequest:
      title: SearchforacustomappdataentryRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforaCustomFieldRequest:
      title: SearchforaCustomFieldRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforacustomfielddataentryRequest:
      title: SearchforacustomfielddataentryRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforanemployeeRequest:
      title: SearchforanemployeeRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforanemployeeagreementRequest:
      title: SearchforanemployeeagreementRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforanEmployeeAgreementHistoryRequest:
      title: SearchforanEmployeeAgreementHistoryRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforanEmployeeAppraisalRequest:
      title: SearchforanEmployeeAppraisalRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforanEmployeeAvailabilityRequest:
      title: SearchforanEmployeeAvailabilityRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforanEmployeeHistoryRequest:
      title: SearchforanEmployeeHistoryRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforanEmployeeRoleRequest:
      title: SearchforanEmployeeRoleRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforanEmployeeWorkplaceRequest:
      title: SearchforanEmployeeWorkplaceRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforanEmploymentConditionRequest:
      title: SearchforanEmploymentConditionRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforanEmploymentContractRequest:
      title: SearchforanEmploymentContractRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforEmploymentContractLeaveRulesRequest:
      title: SearchforEmploymentContractLeaveRulesRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
    SearchforEventsRequest:
      title: SearchforEventsRequest
      required:
      - search
      type: object
      properties:
        search:
          $ref: '#/components/schemas/Search'
      example:
        search:
          s1:
            field: Id
            data: 1
            type: eq
tags:
- name: Resource API
  description: ''
x-provenance:
  method: searched
  source: https://developer.deputy.com/reference
  harvested: '2026-10-14'
  tool: harvest-readme-openapi.py
  note: Assembled verbatim from the OpenAPI definition ReadMe embeds in each operation page of the provider's developer portal; paths and components merged by API title, nothing authored.
  assembled_from:
  - https://developer.deputy.com/reference/getaddresses.md
  - https://developer.deputy.com/reference/getaddressobjectinfo.md
  - https://developer.deputy.com/reference/getcategories.md
  - https://developer.deputy.com/reference/getcategoryobjectinfo.md
  - https://developer.deputy.com/reference/getcommentobjectinfo.md
  - https://developer.deputy.com/reference/getcomments.md
  - https://developer.deputy.com/reference/getcompanyperiodobjectinfo.md
  - https://developer.deputy.com/reference/getcompanyperiods.md
  - https://developer.deputy.com/reference/getcontactobjectinfo.md
  - https://developer.deputy.com/reference/getcountryobjectinfo.md
  - https://developer.deputy.com/reference/getcustomappdataentries.md
  - https://developer.deputy.com/reference/getcustomappdataobjectinfo.md
  - https://developer.deputy.com/reference/getcustomfielddataobjectinfo.md
  - https://developer.deputy.com/reference/getcustomfieldobjectinfo.md
  - https://developer.deputy.com/reference/getcustomfields.md
  - https://developer.deputy.com/reference/getemployeeagreementhistory.md
  - https://developer.deputy.com/reference/getemployeeagreementhistoryobjectinfo.md
  - https://developer.deputy.com/reference/getemployeeagreementobjectinfo.md
  - https://developer.deputy.com/reference/getemployeeagreements.md
  - https://developer.deputy.com/reference/getemployeeappraisalobjectinfo.md
  - https://developer.deputy.com/reference/getemployeeappraisals.md
  - https://developer.deputy.com/reference/getemployeeavailability.md
  - https://developer.deputy.com/reference/getemployeeavailabilityobjectinfo.md
  - https://developer.deputy.com/reference/getemployeehistory.md
  - https://developer.deputy.com/reference/getemployeehistoryobjectinfo.md
  - https://developer.deputy.com/reference/getemployeeobjectinfo.md
  - https://developer.deputy.com/reference/getemployeeroleobjectinfo.md
  - https://developer.deputy.com/reference/getemployeeroles.md
  - https://developer.deputy.com/reference/getemployeeworkplaces.md
  - https://developer.deputy.com/reference/getemploymentconditionobjectinfo.md
  - https://developer.deputy.com/reference/getemploymentconditions.md
  - https://developer.deputy.com/reference/getemploymentcontractleaverules.md
  - https://developer.deputy.com/reference/getemploymentcontractleaverulesobjectinfo.md
  - https://developer.deputy.com/reference/getemploymentcontractobjectinfo.md
  - https://developer.deputy.com/reference/geteventobjectinfo.md
  - https://developer.deputy.com/reference/getevents.md
  - https://developer.deputy.com/reference/getlocations-1.md
  - https://developer.deputy.com/reference/getlocationsobjectinfo.md
  - https://developer.deputy.com/reference/searchforacomment.md
  - https://developer.deputy.com/reference/searchforacompanyperiod.md
  - https://developer.deputy.com/reference/searchforacontact.md
  - https://developer.deputy.com/reference/searchforacountry.md
  - https://developer.deputy.com/reference/searchforacustomappdataentry.md
  - https://developer.deputy.com/reference/searchforacustomfield.md
  - https://developer.deputy.com/reference/searchforacustomfielddataentry.md
  - https://developer.deputy.com/reference/searchforaddress.md
  - https://developer.deputy.com/reference/searchforalocation.md
  - https://developer.deputy.com/reference/searchforanemployee.md
  - https://developer.deputy.com/reference/searchforanemployeeagreement.md
  - https://developer.deputy.com/reference/searchforanemployeeagreementhistory.md
  - https://developer.deputy.com/reference/searchforanemployeeappraisal.md
  - https://developer.deputy.com/reference/searchforanemployeeavailability.md
  - https://developer.deputy.com/reference/searchforanemployeehistory.md
  - https://developer.deputy.com/reference/searchforanemployeerole.md
  - https://developer.deputy.com/reference/searchforanemployeeworkplace.md
  - https://developer.deputy.com/reference/searchforanemploymentcondition.md
  - https://developer.deputy.com/reference/searchforanemploymentcontract.md
  - https://developer.deputy.com/reference/searchforcategory.md
  - https://developer.deputy.com/reference/searchforemploymentcontractleaverules.md
  - https://developer.deputy.com/reference/searchforevents.md
  merge:
    pages: 60
    deduped: 99
    conflicts_kept_first: 0
